[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.lifecycle]
release = "php artisan storage:link && chmod -R 777 storage/app/public && php artisan migrate --force && php artisan optimize" 