version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: ${USER:-laravel}
        uid: ${UID:-1000}
    image: inovalink
    container_name: inovalink-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./public/storage:/var/www/public/storage
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost:8000}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=inovalink
      - DB_USERNAME=inovalink
      - DB_PASSWORD=inovalink
      - SESSION_DRIVER=database
      - CACHE_DRIVER=database
      - QUEUE_CONNECTION=database
      - FILESYSTEM_DISK=public
    networks:
      - inovalink

  # Frontend service for development
  frontend:
    image: node:20
    container_name: inovalink-frontend
    working_dir: /var/www
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_APP_URL=${APP_URL:-http://localhost:8000}
    depends_on:
      - app
    networks:
      - inovalink

  mysql:
    image: mysql:8.0
    container_name: inovalink-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inovalink
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: inovalink
      MYSQL_PASSWORD: inovalink
    ports:
      - "3306:3306"
    volumes:
      - inovalink_mysql_data:/var/lib/mysql
    networks:
      - inovalink

networks:
  inovalink:
    driver: bridge

volumes:
  inovalink_storage:
    driver: local
  inovalink_mysql_data:
    driver: local
